apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels: 
    purpose: deployement-demo
    project: roboshop
    app: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: deployement-demo
    project: roboshop
    app: nginx
  ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: {{ .Values.service.targetPort }} ## service port
